# SPDX-FileCopyrightText: 2024 https://github.com/bobbyxng
#
# SPDX-License-Identifier: MIT

##################
# Initialisation #
##################

import sys
sys.path.append("workflow/scripts")
from _tools import create_symlinks

create_symlinks("data", "workflow/submodules/pypsa-eur-resilient/data")


####################
# Submodule import #
####################

# Define the configuration file
configfile: "workflow/submodules/pypsa-eur-resilient/config/config.default.yaml"
configfile: "config/config.yaml"

# Include the Snakemake workflow from the submodule
module resilient:
    snakefile:
        "submodules/pypsa-eur-resilient/Snakefile"
    config:
        config

# Use all rules from the resilient module
use rule * from resilient


####################
# Additional rules #
####################


