# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
version: v2025.01.0
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

remote:
  ssh: z1
  path: scratch/dev/pypsa-eur-resilient

# PCI-PMI policy paper settings
pcipmi_policy_paper:
  co2_sequestration_min_mt:
    enable: false
    targets:
      2030: 50
      2040: 50 # 150
      2050: 50 # 250
  h2_production_min_mt:
    enable: false
    targets: 
      2030: 10
      2040: 10 # 27.5
      2050: 10 # 35
  electrolyser_capacity_min_gw:
    enable: false
    targets:
      2030: 100
      2040: 100 # 275
      2050: 100 # 350

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: "first-run"
  name: 
  - pcipmi-all-targets
  - pcipmi-no-targets
  - no-pcipmi-all-targets
  - no-pcipmi-no-targets
  scenarios:
    enable: true
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: true # Set to false if problems regarding missing directories occur

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - adm
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  # - 2020
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: enable

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
  transmission_limit: v1.05

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  enable: true
  include:
    pcipmi: true
    tyndp2020: false
    nep: false
    manual: false
  skip:
  - upgraded_lines
  - upgraded_links
  status:
    pcipmi: ['under_construction', 'in_permitting', 'confirmed', 'planned_not_yet_permitted', 'under_consideration']
    tyndp2020: ['under_construction', 'in_permitting', 'confirmed']
    nep: ['under_construction', 'in_permitting', 'confirmed']
  new_link_capacity: keep # keep or zero

carrier_networks:
  CO2:
    enable: true
    include:
      greenfield: true
      pcipmi: true
    extendable:
      greenfield: ['national', 'international']
      pcipmi: []
    p_nom_max: .inf
    options:
      cost_factor: 1.0
      length_factor: 1.0
      delay: 0
  H2:
    enable: true
    include:
      greenfield: true
      pcipmi: true
    extendable:
      greenfield: ['national', 'international']
      pcipmi: []
    p_nom_max: .inf
    options:
      delay: 0
      
pcipmi_projects:
  enable: true
  include: 
    - storage_units_electricity
    - stores_co2
    - stores_h2
  options:
    delay: 0

existing_capacities:
  grouping_years_power: [1920, 1950, 1955, 1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # heat grouping years >= baseyear will be ignored
  threshold_capacity: 10
  default_heating_lifetime: 20
  conventional_carriers:
  - lignite
  - coal
  - oil
  - uranium

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  shipping: true
  aviation: true
  agriculture: true
  fossil_fuels: true
  shipping_hydrogen_liquefaction: false
  shipping_hydrogen_share:
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  shipping_methanol_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.5
    2040: 0.7
    2045: 0.85
    2050: 1
  shipping_oil_share:
    2020: 1
    2025: 0.85
    2030: 0.7
    2035: 0.5
    2040: 0.3
    2045: 0.15
    2050: 0
  shipping_methanol_efficiency: 0.46
  shipping_oil_efficiency: 0.40
  SMR: true
  SMR_cc: true
  regional_oil_demand: true
  regional_coal_demand: false
  regional_co2_sequestration_potential:
    enable: true
    attribute:
    - conservative estimate GAS Mt
    - conservative estimate OIL Mt
    include_onshore: false
    min_size: 3
    max_size: .inf # 25
    years_of_storage: 25
  co2_sequestration_potential:
    2020: 0
    2025: 0
    2030: 50
    2035: 100
    2040: 200
    2045: 200
    2050: 200
  co2_sequestration_cost: 10
  co2_sequestration_lifetime: 50
  co2_spatial: true
  gas_network: true
  H2_retrofit: false
  H2_retrofit_capacity_per_CH4: 0.6
  gas_network_connectivity_upgrade: 1
  gas_distribution_grid: true
  gas_distribution_grid_cost_factor: 1.0
  biomass_spatial: true
  biomass_transport: false
  biogas_upgrading_cc: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  mode: administrative
  administrative:
    level: 1
    DK: 2
    FI: 2
    'NO': 2
    SE: 2
    BA: 0
    BG: 0
    GB: 1
    HR: 0
    RO: 0
    RS: 0
    XK: 0
  temporal:
    resolution_elec: false
    resolution_sector: 3h

  mem_mb: 200000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  memory_logging_frequency: 30 # in seconds
  runtime: 80h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/

plotting:
  balance_map:
    bus_carriers:
    - AC
    - H2
    - co2 stored
    H2:
      unit: TWh
      unit_conversion: 1_000_000
      cmap: Blues
      vmin: 50
      vmax: 100
      region_unit: €/MWh
      bus_factor: 0.002
      branch_factor: 0.04
      flow_factor: 25
      bus_sizes:
      - 50
      - 25
      branch_sizes:
      - 40
      - 20
    co2 stored:
      unit: Mt
      unit_conversion: 1_000_000
      cmap: Purples
      vmin:
      vmax: 
      region_unit: €/t_${CO_2}$
      bus_factor: 0.03
      branch_factor: 0.1
      flow_factor: 150
      bus_sizes:
      - 50
      - 10
      branch_sizes:
      - 5
      - 2
  capacity_map:
    H2:
      unit: TW
      unit_conversion: 1_000_000
      cmap: Blues
      vmin: 50
      vmax: 100
      region_unit: €/MWh
      bus_factor: 0.002
      branch_factor: 0.0003
      flow_factor: 50
      bus_sizes:
      - 50
      - 25
      branch_sizes:
      - 40
      - 20
    co2 stored:
      unit: Mt
      unit_conversion: 1_000_000
      cmap: Purples
      vmin:
      vmax: 
      region_unit: €/t_${CO_2}$
      bus_factor: 200
      branch_factor: 0.001
      flow_factor: 150
      bus_sizes:
      - 0.005
      - 0.001
      branch_sizes:
      - 5
      - 2