pcipmi-all-targets:
  pcipmi_policy_paper:
    co2_sequestration_min_mt:
      enable: true
      targets:
        2030: 50
        2040: 50 # 150
        2050: 50 # 250
    h2_production_min_mt:
      enable: true
      targets: 
        2030: 10
        2040: 10 # 27.5
        2050: 10 # 35
    electrolyser_capacity_min_gw:
      enable: true
      targets:
        2030: 100
        2040: 100 # 275
        2050: 100 # 350

  carrier_networks:
    CO2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: true
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0

pcipmi-no-targets:
  pcipmi_policy_paper:
    co2_sequestration_min_mt:
      enable: false
      targets:
        2030: 50
        2040: 50 # 150
        2050: 50 # 250
    h2_production_min_mt:
      enable: false
      targets: 
        2030: 10
        2040: 10 # 27.5
        2050: 10 # 35
    electrolyser_capacity_min_gw:
      enable: false
      targets:
        2030: 100
        2040: 100 # 275
        2050: 100 # 350

  carrier_networks:
    CO2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: true
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0

no-pcipmi-all-targets:
  pcipmi_policy_paper:
    co2_sequestration_min_mt:
      enable: true
      targets:
        2030: 50
        2040: 50 # 150
        2050: 50 # 250
    h2_production_min_mt:
      enable: true
      targets: 
        2030: 10
        2040: 10 # 27.5
        2050: 10 # 35
    electrolyser_capacity_min_gw:
      enable: true
      targets:
        2030: 100
        2040: 100 # 275
        2050: 100 # 350

  carrier_networks:
    CO2:
      enable: false
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: false
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: false
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0

no-pcipmi-no-targets:
  pcipmi_policy_paper:
    co2_sequestration_min_mt:
      enable: false
      targets:
        2030: 50
        2040: 50 # 150
        2050: 50 # 250
    h2_production_min_mt:
      enable: false
      targets: 
        2030: 10
        2040: 10 # 27.5
        2050: 10 # 35
    electrolyser_capacity_min_gw:
      enable: false
      targets:
        2030: 100
        2040: 100 # 275
        2050: 100 # 350

  carrier_networks:
    CO2:
      enable: false
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: false
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ['national', 'international']
        pcipmi: []
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: false
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0